### ISSUE TITLE
Move https://github.com/darwinia-network/darwinia-polkadotjs-typegen to darwinia.js typegen package

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia.js-1.0-deprecated#2]
And delete polkadot-types

**Comment by hackfisher** [comment]
@WoeOm is darwinia-polkadotjs-typegen archived or not? Do we still need to merge the package?

**Comment by WoeOm** [comment]
darwinia-polkadotjs-typegen can be archived.

**Comment by WoeOm** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/7368203/157005935-3070a7f1-2193-442d-afc1-9fe8495bf925.png">
