### ISSUE TITLE
Multiple Keyring Instances in @darwania/node_modules

### ISSUE THREAD

**Issue by nblogist** [darwinia-network/darwinia.js-1.0-deprecated#3]
**Upon adding @darwania/api and running the following code given in README.md:**

> const { ApiPromise, WsProvider } = require('@darwinia/api');
> 
> async function main () {
>   // Initialise the provider to connect to the local node
>   const provider = new WsProvider('wss://crab.darwinia.network');
> 
>   // Create the API and wait until ready
>   const api = new ApiPromise.create({ provider });
>   await api.isReady;
> 
>   // Retrieve the chain & node information information via rpc calls
>   const [chain, nodeName, nodeVersion] = await Promise.all([
>     api.rpc.system.chain(),
>     api.rpc.system.name(),
>     api.rpc.system.version()
>   ]);
> 
>   console.log(`You are connected to chain ${chain} using ${nodeName} v${nodeVersion}`);
> }
> 
> main().catch(console.error).finally(() => process.exit());

**the following errors pops up:**

> Multiple instances of @polkadot/keyring detected, ensure that there is only one package in your dependency tree.
>         3.5.1   /home/../darwania/node_modules/@darwinia/api/node_modules/@polkadot/api/node_modules/@polkadot/keyring
>         3.3.1   /home/../darwania/node_modules/@darwinia/api/node_modules/@polkadot/keyring

**and**

> TypeError: WsProvider is not a constructor

**Comment by WoeOm** [comment]
It may be that the wrong version is installed, check the package.json, "@darwinia/api": 0.3.0-beta.1^2 or ^1.0.0

**Comment by nblogist** [comment]
using your suggestion with version `^1.0.0` it gives the following error:

> TypeError: ApiPromise.create is not a constructor

with version `0.3.0-beta.1`:

> internal/modules/cjs/loader.js:236
>       throw err;
>       ^
> 
> Error: Cannot find module '/home/.../darwania/node_modules/@darwinia/api/index.js'. Please verify that the package.json has a valid "main" entry

**Comment by WoeOm** [comment]
https://github.com/darwinia-network/darwinia.js/commit/cdb591c4c27a242ee16dd64e29b23679bb8405a6

**Comment by nblogist** [comment]
This is solved now. https://github.com/darwinia-network/darwinia.js/commit/cdb591c4c27a242ee16dd64e29b23679bb8405a6
Thanks @WoeOm !
