### ISSUE TITLE
Support metadata v14 Pangolin

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia.js-1.0-deprecated#47]
Report from user:

> Cloud you tell me the pangolin network currently updated?
> I was using @darwinia/types to connect Crab & Pangolin.
> const apiPromise = await ApiPromise.create({
>          provider: provider,
>          typesBundle: darwiniaTypesBundle,
>        });
> 2 days ago, I found I can't connect Pangolin. But I can connect Crab and Kusama still now.
> This is error screen.
> Any opinion?

![file_39](https://user-images.githubusercontent.com/1070122/150082008-ec3672dd-3d93-4f3d-90b7-18bf9412ea71.jpg)

**Comment by sxlwar** [comment]
The error is caused by Rang types error in Polkadot metaV14. https://github.com/polkadot-js/api/issues/4453

**Comment by hackfisher** [comment]
Fixed in upstream, should be able to fix it by using the latest `@polkadot/api`
