### ISSUE TITLE
Fix gen types error

### ISSUE THREAD

**Issue by sxlwar** [darwinia-network/darwinia.js-1.0-deprecated#48]
branch: types

after running `generate:defs`, there are many type errors in types.ts. Cause unusable and incorrect interfaces in business projects

https://github.com/darwinia-network/wormhole-ui/issues/163

apps-lite tx method call

**Comment by hackfisher** [comment]
@sxlwar Does this issue still exist?

**Comment by sxlwar** [comment]
> @sxlwar Does this issue still exist?

yeah,  have not seen the new version yet. 

Will be fixed by #57
