### ISSUE TITLE
Improve key packages description

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia.js-1.0-deprecated#50]
- @polkaodt/api : API framework package for substrate chains.

- Packages for darwinia's chains:
  - @darwinia/types : Definition of customize types for Darwinia's chains(Darwinia, Crab, Crab parachain, Pangolin/Pangoro etc), for blocks before Substrate Metadata V14. Probably not used by @polkaodt/api for blocks>= Substrate Metadata V14.  @polkaodt/api is supposed to handle for different Metadata automaticlly.
  - @darwinia/api-derive: TBD. Derived api for darwinia.
  - @darwinia/rpc:   TBD. RPC definition for darwinia customized rpcs.

- @darwinia/api-options:   Sample and easy options with @darwinia/types, @darwinia/api-derive, @darwinia/rpc as default settings.

**Comment by cinlk** [comment]
> * @polkaodt/api : API framework package for substrate chains.
> * Packages for darwinia's chains:
>   
>   * @darwinia/types : Definition of customize types for Darwinia's chains(Darwinia, Crab, Crab parachain, Pangolin/Pangoro etc), for blocks before Substrate Metadata V14. Probably not used by @polkaodt/api for blocks>= Substrate Metadata V14.  @polkaodt/api is supposed to handle for different Metadata automaticlly.
>   * @darwinia/api-derive: TBD. Derived api for darwinia.
>   * @darwinia/rpc:   TBD. RPC definition for darwinia customized rpcs.
> * @darwinia/api-options:   Sample and easy options with @darwinia/types, @darwinia/api-derive, @darwinia/rpc as default settings.

**Comment by cinlk** [comment]
> * @polkaodt/api : API framework package for substrate chains.
> * Packages for darwinia's chains:
>   
>   * @darwinia/types : Definition of customize types for Darwinia's chains(Darwinia, Crab, Crab parachain, Pangolin/Pangoro etc), for blocks before Substrate Metadata V14. Probably not used by @polkaodt/api for blocks>= Substrate Metadata V14.  @polkaodt/api is supposed to handle for different Metadata automaticlly.
>   * @darwinia/api-derive: TBD. Derived api for darwinia.
>   * @darwinia/rpc:   TBD. RPC definition for darwinia customized rpcs.
> * @darwinia/api-options:   Sample and easy options with @darwinia/types, @darwinia/api-derive, @darwinia/rpc as default settings.

done in #55
