### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia.js-1.0-deprecated#54]
- `yarn add @darwinia/api-options` should be `yarn add @darwinia/types`
- #50 
- List well known projects which are using darwinia.js, including
  - Darwinia apps
  - wormhole-ui
  - https://github.com/polkadot-js/apps/tree/master/packages/apps-config
  - https://github.com/darwinia-network/staking-payouts
  - Subquery projects.
- Improve readability and clarity

**Comment by cinlk** [comment]
done in #55

**Comment by cinlk** [comment]
> * `yarn add @darwinia/api-options` should be `yarn add @darwinia/types`
> * [Improve key packages description #50](https://github.com/darwinia-network/darwinia.js/issues/50)
> * List well known projects which are using darwinia.js, including
>   
>   * Darwinia apps
>   * wormhole-ui
>   * https://github.com/polkadot-js/apps/tree/master/packages/apps-config
>   * https://github.com/darwinia-network/staking-payouts
>   * Subquery projects.
> * Improve readability and clarity

done in #55
