### ISSUE TITLE
Update dependance for pangolin network  in  polkadot official repo

### ISSUE THREAD

**Issue by sxlwar** [darwinia-network/darwinia.js-1.0-deprecated#7]
![image](https://user-images.githubusercontent.com/20088392/120433941-6881e080-c3ae-11eb-9782-4cfd9c03f10d.png)

repo: https://github.com/polkadot-js/apps

path: packages/app-config

dep: @darwinia/types

**Comment by acgxv** [comment]
These types are a part of s2s. They are common types.

I don't know if it's good to place them in darwinia types.

**Comment by hackfisher** [comment]
@fewensa If these types are from parity-bridge-common, which is also third-party to substrate&polkadot.js, maybe we should put it simply in darwinia types since polkadot.js will not automatically handle it.

parity-bridge-common can maintain a type.json file for darwinia types as a reference.

**Comment by sxlwar** [comment]
fixed by this [pr](https://github.com/polkadot-js/apps/pull/5459)

I will close this issue,  anything else to discuss pls reopen it or create another issue.
